#!/bin/sh -p
### SASGSUB 92 Execution Script                              

JAVA_HOME=/sasfs/prod/java/jre32/jre1.6.0_16
export JAVA_HOME

LD_LIBRARY_PATH=$JAVA_HOME/lib/i386/server:$JAVA_HOME/lib/i386:/sasfs/prod/sas/92/sasgsubclient/sashome/SASGridManagerClientUtility/9.2/bin:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

/sasfs/prod/sas/92/sasgsubclient/sashome/SASGridManagerClientUtility/9.2/bin/sasgsub -GRIDCONFIG /sasfs/sasgsub_prod/sasgsubp92.cfg $*
